### ISSUE TITLE
Link to .bib file is dead

### ISSUE THREAD

**Issue by Auios** [ashoulson/ADAPT#6]
This link in the read me is dead: http://www.seas.upenn.edu/~shoulson/papers/2014-tvcg-adapt.bib

**Comment by Auios** [comment]
Why did you close it? It's not fixed

**Comment by ashoulson** [comment]
Odd. GitHub doesn't like linking to .bib files for some reason. I've included the paper, its supplement, and its BibTeX in the github repo itself now.
